### ISSUE TITLE
Drop commit rights for @bexelbie

### ISSUE THREAD

**Issue by bexelbie** [CentOS/Calendar#28]
It looks like we may no longer be using this calendar (or it isn't doesn't change much).  I haven't really been thinking about helping here and suggest that I be replaced by @rbowen.

I plan to drop my commit rights on 31 Jan 2019 unless someone asks me to keep them to help with a smooth transition.

**Comment by arrfab** [comment]
@rbowen invited and I've removed your commit rights. Thanks for your help and support :-)
